version: '3.8'

services:
  emqx:
    image: emqx/emqx:5.3.2
    container_name: nosky_emqx_broker
    ports:
      - "1883:1883"
      - "8883:8883"
      - "18083:18083"
    environment:
      - EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__ENABLE=true
      - EMQX_LISTENERS__TCP__DEFAULT__AUTHENTICATION__1__MECHANISM=enhanced_auth
    volumes:
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf

  redis:
    image: redis:7.2-alpine
    container_name: nosky_redis_cache
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel notice
